### ISSUE TITLE
Problem with scanner in windows 10

### ISSUE THREAD

**Issue by AlTahish** [Miladkhoshdel/burp-to-sqlmap#6]
Great Work Mr Milad

I followed all steps as you explain when the script start and export packect completed
this error is coming to my cmd screen:
`632 Packets Exported Successfully.

 [+] Testing SQL Injection on packets ...  (Based on your network connection Test can take up to 5 minutes.)
   [-] Performing SQL Injection on packet number 1. Please Wait ...
Traceback (most recent call last):
  File "C:\Users\WhatUpTime.com\Downloads\Telegram Desktop\burp-to-sqlmap-master\burp-to-sqlmap-master\burp-to-sqlmap.py", line 191, in <module>
    main()
  File "C:\Users\WhatUpTime.com\Downloads\Telegram Desktop\burp-to-sqlmap-master\burp-to-sqlmap-master\burp-to-sqlmap.py", line 95, in main
    runWindows(filename, directory, sqlmappath, proxyvalue, vulnerablefiles, risk_value, level_value, tamper_value)
  File "C:\Users\WhatUpTime.com\Downloads\Telegram Desktop\burp-to-sqlmap-master\burp-to-sqlmap-master\burp-to-sqlmap.py", line 121, in runWindows
    if 'is vulnerable' in open(directory + "\\testresult" + file).read() or "Payload:" in open(
FileNotFoundError: [Errno 2] No such file or directory: 'mm\\testresult1.txt'
`
My OS: Windows 10

**Comment by Miladkhoshdel** [comment]
Dear AlTahish,

Thank You and sorry for my delay to check your issue. How did you run the script? would you please send your executed command if the problem exists yet. 

Thank You

**Comment by Miladkhoshdel** [comment]
Dear AlTahish,

Would you please update me ?
